variable "cluster_name" {}
variable "db_name" {}
variable "node_type" {}
variable "cluster_type" {}
variable "nodes" {}
variable "subnet_group_name" {}
variable "enhanced" {}
variable "iam_roles" {}
variable "sg_count" {}
variable "count" {}
variable "final_snap" {}
variable "subnet" {}
variable "availability_zone" {}
variable "master_sg" {}
#variable "vpc_id" {}